title: Scotty Franzyshen
logo: /images/New_logo.png
description: Housing, employment, community, and life in Butte County
favicon: /sfranzyshen.github.io/favicon.ico
theme: jekyll-theme-minimal
google_analytics: G-JNYKS671WD
url: "https://sfranzyshen.org"
