title: Scotty Franzyshen
logo: /New_logo.png
description: Housing, employment, community, and life in Butte County
favicon: /sfranzyshen.github.io/favicon.ico
theme: jekyll-theme-minimal
url: "https://sfranzyshen.org"
